version: 2

jobs:
  publish-itchio:
    docker:
      - image: debian:latest
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get -y install curl wget zip unzip
      - run:
          name: Install git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
            apt-get install git-lfs -y
      - checkout
      - run:
          name: Download Godot 3.2.3
          command: |
            wget -q https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_linux_headless.64.zip
            unzip Godot_v3.2.3-stable_linux_headless.64.zip
            mv Godot_v3.2.3-stable_linux_headless.64 godot
            chmod +x godot
      - run:
          name: Download Godot 3.2.3 Export Templates
          command: |
            wget -q https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_export_templates.tpz
            mkdir -p ~/.local/share/godot/templates
            unzip Godot_v3.2.3-stable_export_templates.tpz -d ~/.local/share/godot/templates
            mv ~/.local/share/godot/templates/templates ~/.local/share/godot/templates/3.2.3.stable
      - run:
          name: Download butler
          command: |
            wget -q -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
            unzip butler.zip
            chmod +x butler
      - run:
          name: Export Web build
          command: |
            mkdir -p web
            ./godot -v --export-debug "HTML5" project.godot "web/index.html"
            zip -r web.zip web
      - run:
          name: Upload Web build
          command: ./butler push web.zip yakovko/ace-invaders:web

workflows:
  version: 2
  build-deploy:
    jobs:
      - publish-itchio:
          filters:
            branches:
              only:
                - main
